export interface Hangman {
  id: number;
  word: string;
};

export const HangmanData = [
  { id: 1, word: "waltz" },
  { id: 2, word: "gypsy" },
  { id: 3, word: "subway" },
  { id: 4, word: "espionage" },
  { id: 5, word: "yodel" },
  { id: 6, word: "avenue" },
  { id: 7, word: "absurd" },
  { id: 8, word: "labyrinth" },
  { id: 9, word: "croquet" },
  { id: 10, word: "haphazard" },
  { id: 11, word: "kazoo" },
  { id: 12, word: "jazzy" },
  { id: 13, word: "embezzle" },
  { id: 14, word: "sphinx" },
  { id: 15, word: "bikini" },
  { id: 16, word: "yacht" },
  { id: 17, word: "zigzag" },
  { id: 18, word: "buzzing" },
  { id: 19, word: "quicksand" },
  { id: 20, word: "crypt" },
  { id: 21, word: "xylophone" },
  { id: 22, word: "bagpipes" },
  { id: 23, word: "bookworm" },
  { id: 24, word: "megabyte" },
  { id: 25, word: "hyphen" },
  { id: 26, word: "jigsaw" },
  { id: 27, word: "boxcar" },
  { id: 28, word: "voodoo" },
  { id: 29, word: "ivory" },
  { id: 30, word: "nirvana" },
  { id: 31, word: "banjo" },
  { id: 32, word: "equip" },
  { id: 33, word: "rhythm" },
  { id: 34, word: "haiku" },
  { id: 35, word: "zealot" },
  { id: 36, word: "quartz" },
  { id: 37, word: "dwarves" },
  { id: 38, word: "zebra" },
  { id: 39, word: "tombstone" },
  { id: 40, word: "cockiness" },
  { id: 41, word: "razzmatazz" },
  { id: 42, word: "whimsical" },
  { id: 43, word: "fishhook" },
  { id: 44, word: "oasis" },
  { id: 45, word: "gazebo" },
  { id: 46, word: "memento" },
  { id: 47, word: "yellow" },
  { id: 48, word: "vagabond" },
  { id: 49, word: "exodus" },
  { id: 50, word: "onxy" },
  { id: 51, word: "kaleidoscope" },
  { id: 52, word: "tangerine" },
  { id: 53, word: "zombie" },
  { id: 54, word: "pizzazz" },
  { id: 56, word: "memento" },
  { id: 58, word: "oasis" },
  { id: 60, word: "quicksand" },
  { id: 61, word: "rhythm" },
  { id: 62, word: "sapphire" },
  { id: 63, word: "tangerine" },
  { id: 65, word: "vagabond" },
  { id: 66, word: "whimsical" },
  { id: 69, word: "zealous" }
];
