export interface Hangman {
  id: number;
  word: string;
};

export const HangmanData = [
{ id: 1, word: "abruptly" },
{ id: 2, word: "absurd" },
{ id: 3, word: "avenue" },
{ id: 4, word: "awkward" },
{ id: 5, word: "bagpipes" },
{ id: 6, word: "banjo" },
{ id: 7, word: "bikini" },
{ id: 8, word: "blitz" },
{ id: 9, word: "bookworm" },
{ id: 10, word: "boxcar" },
{ id: 11, word: "buffalo" },
{ id: 12, word: "buzzing" },
{ id: 13, word: "cockiness" },
{ id: 14, word: "croquet" },
{ id: 15, word: "crypt" },
{ id: 16, word: "dwarves" },
{ id: 17, word: "embezzle" },
{ id: 18, word: "equip" },
{ id: 19, word: "espionage" },
{ id: 20, word: "exodus" },
{ id: 21, word: "fishhook" },
{ id: 22, word: "gazebo" },
{ id: 23, word: "gypsy" },
{ id: 24, word: "haiku" },
{ id: 25, word: "haphazard" },
{ id: 26, word: "hyphen" },
{ id: 27, word: "injury" },
{ id: 28, word: "ivory" },
{ id: 29, word: "jazzy" },
{ id: 30, word: "jigsaw" },
{ id: 31, word: "kazoo" },
{ id: 32, word: "labyrinth" },
{ id: 33, word: "megabyte" },
{ id: 34, word: "nirvana" },
{ id: 35, word: "onyx" },
{ id: 36, word: "pajama" },
{ id: 37, word: "quartz" },
{ id: 38, word: "razzmatazz" },
{ id: 39, word: "sphinx" },
{ id: 40, word: "subway" },
{ id: 41, word: "tombstone" },
{ id: 42, word: "ubiquitous" },
{ id: 43, word: "vacuum" },
{ id: 44, word: "voodoo" },
{ id: 45, word: "waltz" },
{ id: 46, word: "xylophone" },
{ id: 47, word: "yacht" },
{ id: 48, word: "yodel" },
{ id: 49, word: "zealot" },
{ id: 50, word: "zebra" },
{ id: 51, word: "zenith" },
{ id: 52, word: "zigzag" },
{ id: 53, word: "zodiac"},  
{ id: 54, word: "kaleidoscope" },
{ id: 55, word: "labyrinth" },
{ id: 56, word: "memento" },
{ id: 57, word: "nirvana" },
{ id: 58, word: "oasis" },
{ id: 59, word: "pajama" },
{ id: 60, word: "quicksand" },
{ id: 61, word: "rhythm" },
{ id: 62, word: "sapphire" },
{ id: 63, word: "tangerine" },
{ id: 64, word: "ubiquitous" },
{ id: 65, word: "vagabond" },
{ id: 66, word: "whimsical" },
{ id: 67, word: "queue" },
{ id: 68, word: "yellow" },
{ id: 69, word: "zealous" }
];
